# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-14 13:51
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0014_courseoverview_certificate_available_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRatingAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_rating_answers', to='course_overviews.CourseOverview')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRatingOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('rating_count', models.IntegerField(default=0)),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_rating_overview', to='course_overviews.CourseOverview')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRatingQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_rating_questions', to='course_overviews.CourseOverview')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to='course_overviews.CourseOverview')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courseratinganswers',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_rating_answers', to='course_rating.CourseRatingQuestions'),
        ),
        migrations.AddField(
            model_name='courseratinganswers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_rating_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='courseratings',
            unique_together=set([('user_id', 'course_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='courseratinganswers',
            unique_together=set([('user_id', 'course_id', 'question_id')]),
        ),
    ]
